name: Rust

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

  # Make sure CI fails on all warnings, including Clippy lints
  # RUSTFLAGS: --deny warnings

jobs:
  build:

    strategy:
      matrix:
        platform:
          - os: ubuntu

    runs-on: ${{ matrix.platform.os }}-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Cache
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Display build versions
        run: |
          cargo --version
          rustc --version
          rustup toolchain list
          cargo clippy --version
          jq --version

      - name: Build
        run: cargo build

      - name: Test
        run: cargo test

      # Run Clippy and convert compiler messages to GitHub annotations
      - name: Clippy
        shell: bash
        run: >-
          cargo clippy -q --all-targets --all-features --message-format=json
          | jq -r 'select(.reason == "compiler-message")
            | .message
            | . as $message
            | .spans[]
            | select(.is_primary)
            | "::\($message.level) file=\(.file_name),line=\(.line_start),endLine=\(.line_end),col=\(.column_start),endColumn=\(.column_end),title=Clippy::\($message.message)"'
